Persist nav bar open/closed state across visits/refreshes
blackjackkent/RPThreadTrackerV3.FrontEnd pull request #137
Opened 2019-05-27 17:53 UTC by wharrrgarbl

This is mostly re-using the same machinery that persists the light/dark theme.

2019-05-29 16:11 UTC, blackjackkent requested changes
This looks great! Straightforward and in line with existing patterns. Thanks for submitting. :) Made a request for some small stylistic nitpicks but other than that this looks fine.

2019-05-29 16:11 UTC, blackjackkent commented on src/display/shared/header/HeaderContainer.js
> +	loadSideBarOpen: PropTypes.func.isRequired,
Nitpick for stylistic consistency: `Sidebar` rather than `SideBar` please? :)

2019-05-29 16:11 UTC, blackjackkent commented on src/display/shared/header/HeaderContainer.js
> +		const { loadSideBarOpen, setSideBarOpen, ...props } = this.props;
Nice cleanliness tweak. :)

2019-05-29 16:11 UTC, blackjackkent commented on src/infrastructure/sagas/ui/setSiteThemeSaga.js
> +export default function* setSiteThemeSaga() {
Haha nice catch. :D Got bitten by copypasta, looks like.

2019-05-29 16:11 UTC, blackjackkent commented on src/display/shared/header/HeaderContainer.js
> +	loadSideBarOpen: PropTypes.func.isRequired,
Also SIDEBAR instead of SIDE_BAR

2019-05-29 17:34 UTC, wharrrgarbl commented on src/display/shared/header/HeaderContainer.js
> +	loadSideBarOpen: PropTypes.func.isRequired,
👍 Done

2019-06-10 19:35 UTC, blackjackkent approved these changes
This is looking good! Thanks for your patience on the delay in reviewing; this month is insane for me.

2019-06-10 19:36 UTC, merged